import ContextProvider from "./contextProvider";
import "./globals.css";

export const metadata = {
  title: "مای‌سنتر",
  description: "مدیریت مالی گیم‌سنتر",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="fa">
      <meta name="enamad" content="275943" />
      <body className="light light_blue bg-tritary">
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
