import Footer from "@/components/footer";
import Header from "@/components/header";
import ContextProvider from "./contextProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="fa">
      <body className="light light_blue bg-tritary">
          <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
